export const constants = {
    // RSTUDIO_INSTANCE: process.env.RSTUDIO_INSTANCE,
    // BUCKET_NAME: process.env.BUCKET_NAME,
    // DYNAMODB_FILES_GSI: process.env.DYNAMODB_FILES_GSI,
    // DYNAMODB_FILES_TABLE: process.env.DYNAMODB_FILES_TABLE,
    // DYNAMODB_JOBS_STATE_GSI: process.env.DYNAMODB_JOBS_STATE_GSI,
    // DYNAMODB_JOBS_TIME_GSI: process.env.DYNAMODB_JOBS_TIME_GSI,
    // DYNAMODB_JOBS_TABLE: process.env.DYNAMODB_JOBS_TABLE,
    // DYNAMODB_OPTIONS: {},
    // GLUE_JOB_NAME: process.env.GLUE_JOB_NAME,
    // SIGNED_URL_EXPIRE_SECONDS: 60 * 60,


    ENVIRONMENT: process.env.ENVIRONMENT,
    COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    REGION: process.env.REGION,
    STAGE: process.env.STAGE,
    DYNAMODB_TABLE: process.env.DYNAMODB_TABLE,
    DYNAMODB_MEMBER_CHAT_GSI: process.env.DYNAMODB_MEMBER_CHAT_GSI,
    KEYS_URL: process.env.KEYS_URL,
    WEBSOCKET_API_ENDPOINT: process.env.WEBSOCKET_API_ENDPOINT,
}